/// <mls fileReference="_102045_/l4/buildFlowFsm/ontology/DelayRiskSuggestion.defs.ts" enhancement="_blank"/>

export const buildFlowFsmEntityDelayRiskSuggestion = {
  "entityId": "DelayRiskSuggestion",
  "title": "Delay Risk Suggestion",
  "description": "An AI-generated advisory flag identifying a task at risk of delay, tied to a status report and referencing the specific work task without automatically changing its status.",
  "kind": "supporting",
  "ownership": "moduleOwned",
  "fields": [
    {
      "fieldId": "delayRiskSuggestionId",
      "type": "uuid",
      "required": true,
      "description": "Primary identifier for the delay-risk suggestion."
    },
    {
      "fieldId": "statusReportId",
      "type": "uuid",
      "required": true,
      "description": "Reference to the status report that contains this suggestion."
    },
    {
      "fieldId": "workTaskId",
      "type": "uuid",
      "required": true,
      "description": "Reference to the work task flagged as at risk of delay."
    },
    {
      "fieldId": "riskLevel",
      "type": "string",
      "required": true,
      "description": "Severity of the delay risk as assessed by the AI.",
      "enum": [
        "low",
        "medium",
        "high"
      ]
    },
    {
      "fieldId": "reason",
      "type": "text",
      "required": true,
      "description": "AI-generated explanation of why the task is at risk, based on time logs, material usage and task progress."
    },
    {
      "fieldId": "suggestedAction",
      "type": "text",
      "required": false,
      "description": "Optional recommended action to mitigate the delay risk."
    },
    {
      "fieldId": "acknowledged",
      "type": "boolean",
      "required": true,
      "description": "Whether the project manager has reviewed and acknowledged this advisory suggestion."
    },
    {
      "fieldId": "createdAt",
      "type": "datetime",
      "required": true,
      "description": "Timestamp when the suggestion was generated by the AI."
    },
    {
      "fieldId": "updatedAt",
      "type": "datetime",
      "required": true,
      "description": "Timestamp of the last modification to the suggestion."
    }
  ]
} as const;

export default buildFlowFsmEntityDelayRiskSuggestion;
