/// <mls fileReference="_102045_/l2/buildFlowFsm/web/shared/clientManagementWorkspace.test.ts" enhancement="_102020_/l2/enhancementAura"/>

import type { BuildFlowFsmClientManagementWorkspaceBase } from '/_102045_/l2/buildFlowFsm/web/shared/clientManagementWorkspace.js';
import type { CreateClientCmdInput, CreateClientCmdOutput, DeleteClientCmdInput, DeleteClientCmdOutput, ListClientsInput, ListClientsOutput, UpdateClientCmdInput, UpdateClientCmdOutput } from '/_102045_/l2/buildFlowFsm/web/contracts/clientManagementWorkspace.js';

type IsAny<T> = 0 extends (1 & T) ? true : false;
type Assignable<Actual, Expected> = IsAny<Actual> extends true ? false : [Actual] extends [Expected] ? true : false;
type Assert<T extends true> = T;

declare const page: BuildFlowFsmClientManagementWorkspaceBase;

// This file is generated from .defs.ts. Add narrower state/action assertions here as materialization rules evolve.
type _State_status = Assert<Assignable<typeof page.status, string>>;
type _State_listClientsState = Assert<Assignable<typeof page.listClientsState, "idle" | "loading" | "success" | "error">>;
type _State_listClientsName = Assert<Assignable<typeof page.listClientsName, string | ListClientsInput["name"]>>;
type _State_listClientsCompany = Assert<Assignable<typeof page.listClientsCompany, string | ListClientsInput["company"]>>;
type _State_listClientsEmail = Assert<Assignable<typeof page.listClientsEmail, string | ListClientsInput["email"]>>;
type _State_listClientsPage = Assert<Assignable<typeof page.listClientsPage, string | ListClientsInput["page"]>>;
type _State_listClientsPageSize = Assert<Assignable<typeof page.listClientsPageSize, string | ListClientsInput["pageSize"]>>;
type _State_listClientsData = Assert<Assignable<typeof page.listClientsData, ListClientsOutput>>;
type _State_createClientCmdState = Assert<Assignable<typeof page.createClientCmdState, "idle" | "loading" | "success" | "error">>;
type _State_createClientCmdName = Assert<Assignable<typeof page.createClientCmdName, string | CreateClientCmdInput["name"]>>;
type _State_createClientCmdEmail = Assert<Assignable<typeof page.createClientCmdEmail, string | CreateClientCmdInput["email"]>>;
type _State_createClientCmdCompany = Assert<Assignable<typeof page.createClientCmdCompany, string | CreateClientCmdInput["company"]>>;
type _State_createClientCmdPhone = Assert<Assignable<typeof page.createClientCmdPhone, string | CreateClientCmdInput["phone"]>>;
type _State_createClientCmdAddress = Assert<Assignable<typeof page.createClientCmdAddress, string | CreateClientCmdInput["address"]>>;
type _State_createClientCmdOutput = Assert<Assignable<typeof page.createClientCmdOutput, CreateClientCmdOutput | null>>;
type _State_createClientCmdError = Assert<Assignable<typeof page.createClientCmdError, string>>;
type _State_updateClientCmdState = Assert<Assignable<typeof page.updateClientCmdState, "idle" | "loading" | "success" | "error">>;
type _State_updateClientCmdClientId = Assert<Assignable<typeof page.updateClientCmdClientId, string | UpdateClientCmdInput["clientId"]>>;
type _State_updateClientCmdName = Assert<Assignable<typeof page.updateClientCmdName, string | UpdateClientCmdInput["name"]>>;
type _State_updateClientCmdCompany = Assert<Assignable<typeof page.updateClientCmdCompany, string | UpdateClientCmdInput["company"]>>;
type _State_updateClientCmdEmail = Assert<Assignable<typeof page.updateClientCmdEmail, string | UpdateClientCmdInput["email"]>>;
type _State_updateClientCmdPhone = Assert<Assignable<typeof page.updateClientCmdPhone, string | UpdateClientCmdInput["phone"]>>;
type _State_updateClientCmdAddress = Assert<Assignable<typeof page.updateClientCmdAddress, string | UpdateClientCmdInput["address"]>>;
type _State_updateClientCmdOutput = Assert<Assignable<typeof page.updateClientCmdOutput, UpdateClientCmdOutput | null>>;
type _State_updateClientCmdError = Assert<Assignable<typeof page.updateClientCmdError, string>>;
type _State_deleteClientCmdState = Assert<Assignable<typeof page.deleteClientCmdState, "idle" | "loading" | "success" | "error">>;
type _State_deleteClientCmdClientId = Assert<Assignable<typeof page.deleteClientCmdClientId, string | DeleteClientCmdInput["clientId"]>>;
type _State_deleteClientCmdOutput = Assert<Assignable<typeof page.deleteClientCmdOutput, DeleteClientCmdOutput | null>>;
type _State_deleteClientCmdError = Assert<Assignable<typeof page.deleteClientCmdError, string>>;
type _Action_loadListClients = Assert<Assignable<typeof page.loadListClients, (...args: any[]) => unknown>>;
type _Handler_handleListClientsClick = Assert<Assignable<typeof page.handleListClientsClick, (...args: any[]) => unknown>>;
type _Action_createClientCmd = Assert<Assignable<typeof page.createClientCmd, (...args: any[]) => unknown>>;
type _Handler_handleCreateClientCmdClick = Assert<Assignable<typeof page.handleCreateClientCmdClick, (...args: any[]) => unknown>>;
type _Action_updateClientCmd = Assert<Assignable<typeof page.updateClientCmd, (...args: any[]) => unknown>>;
type _Handler_handleUpdateClientCmdClick = Assert<Assignable<typeof page.handleUpdateClientCmdClick, (...args: any[]) => unknown>>;
type _Action_deleteClientCmd = Assert<Assignable<typeof page.deleteClientCmd, (...args: any[]) => unknown>>;
type _Handler_handleDeleteClientCmdClick = Assert<Assignable<typeof page.handleDeleteClientCmdClick, (...args: any[]) => unknown>>;
type _Action_setListClientsName = Assert<Assignable<typeof page.setListClientsName, (...args: any[]) => unknown>>;
type _Handler_handleListClientsNameChange = Assert<Assignable<typeof page.handleListClientsNameChange, (...args: any[]) => unknown>>;
type _Action_setListClientsCompany = Assert<Assignable<typeof page.setListClientsCompany, (...args: any[]) => unknown>>;
type _Handler_handleListClientsCompanyChange = Assert<Assignable<typeof page.handleListClientsCompanyChange, (...args: any[]) => unknown>>;
type _Action_setListClientsEmail = Assert<Assignable<typeof page.setListClientsEmail, (...args: any[]) => unknown>>;
type _Handler_handleListClientsEmailChange = Assert<Assignable<typeof page.handleListClientsEmailChange, (...args: any[]) => unknown>>;
type _Action_setListClientsPage = Assert<Assignable<typeof page.setListClientsPage, (...args: any[]) => unknown>>;
type _Handler_handleListClientsPageChange = Assert<Assignable<typeof page.handleListClientsPageChange, (...args: any[]) => unknown>>;
type _Action_setListClientsPageSize = Assert<Assignable<typeof page.setListClientsPageSize, (...args: any[]) => unknown>>;
type _Handler_handleListClientsPageSizeChange = Assert<Assignable<typeof page.handleListClientsPageSizeChange, (...args: any[]) => unknown>>;
type _Action_setCreateClientCmdName = Assert<Assignable<typeof page.setCreateClientCmdName, (...args: any[]) => unknown>>;
type _Handler_handleCreateClientCmdNameChange = Assert<Assignable<typeof page.handleCreateClientCmdNameChange, (...args: any[]) => unknown>>;
type _Action_setCreateClientCmdEmail = Assert<Assignable<typeof page.setCreateClientCmdEmail, (...args: any[]) => unknown>>;
type _Handler_handleCreateClientCmdEmailChange = Assert<Assignable<typeof page.handleCreateClientCmdEmailChange, (...args: any[]) => unknown>>;
type _Action_setCreateClientCmdCompany = Assert<Assignable<typeof page.setCreateClientCmdCompany, (...args: any[]) => unknown>>;
type _Handler_handleCreateClientCmdCompanyChange = Assert<Assignable<typeof page.handleCreateClientCmdCompanyChange, (...args: any[]) => unknown>>;
type _Action_setCreateClientCmdPhone = Assert<Assignable<typeof page.setCreateClientCmdPhone, (...args: any[]) => unknown>>;
type _Handler_handleCreateClientCmdPhoneChange = Assert<Assignable<typeof page.handleCreateClientCmdPhoneChange, (...args: any[]) => unknown>>;
type _Action_setCreateClientCmdAddress = Assert<Assignable<typeof page.setCreateClientCmdAddress, (...args: any[]) => unknown>>;
type _Handler_handleCreateClientCmdAddressChange = Assert<Assignable<typeof page.handleCreateClientCmdAddressChange, (...args: any[]) => unknown>>;
type _Action_setUpdateClientCmdClientId = Assert<Assignable<typeof page.setUpdateClientCmdClientId, (...args: any[]) => unknown>>;
type _Handler_handleUpdateClientCmdClientIdChange = Assert<Assignable<typeof page.handleUpdateClientCmdClientIdChange, (...args: any[]) => unknown>>;
type _Action_setUpdateClientCmdName = Assert<Assignable<typeof page.setUpdateClientCmdName, (...args: any[]) => unknown>>;
type _Handler_handleUpdateClientCmdNameChange = Assert<Assignable<typeof page.handleUpdateClientCmdNameChange, (...args: any[]) => unknown>>;
type _Action_setUpdateClientCmdCompany = Assert<Assignable<typeof page.setUpdateClientCmdCompany, (...args: any[]) => unknown>>;
type _Handler_handleUpdateClientCmdCompanyChange = Assert<Assignable<typeof page.handleUpdateClientCmdCompanyChange, (...args: any[]) => unknown>>;
type _Action_setUpdateClientCmdEmail = Assert<Assignable<typeof page.setUpdateClientCmdEmail, (...args: any[]) => unknown>>;
type _Handler_handleUpdateClientCmdEmailChange = Assert<Assignable<typeof page.handleUpdateClientCmdEmailChange, (...args: any[]) => unknown>>;
type _Action_setUpdateClientCmdPhone = Assert<Assignable<typeof page.setUpdateClientCmdPhone, (...args: any[]) => unknown>>;
type _Handler_handleUpdateClientCmdPhoneChange = Assert<Assignable<typeof page.handleUpdateClientCmdPhoneChange, (...args: any[]) => unknown>>;
type _Action_setUpdateClientCmdAddress = Assert<Assignable<typeof page.setUpdateClientCmdAddress, (...args: any[]) => unknown>>;
type _Handler_handleUpdateClientCmdAddressChange = Assert<Assignable<typeof page.handleUpdateClientCmdAddressChange, (...args: any[]) => unknown>>;
type _Action_setDeleteClientCmdClientId = Assert<Assignable<typeof page.setDeleteClientCmdClientId, (...args: any[]) => unknown>>;
type _Handler_handleDeleteClientCmdClientIdChange = Assert<Assignable<typeof page.handleDeleteClientCmdClientIdChange, (...args: any[]) => unknown>>;

export {};