/// <mls fileReference="_102045_/l2/buildFlowFsm/web/shared/projectDetailWorkspace.test.ts" enhancement="_102020_/l2/enhancementAura"/>

import type { BuildFlowFsmProjectDetailWorkspaceBase } from '/_102045_/l2/buildFlowFsm/web/shared/projectDetailWorkspace.js';
import type { GetChangeOrderDetailInput, GetChangeOrderDetailOutput, GetProjectDetailInput, GetProjectDetailOutput, ListChangeOrdersInput, ListChangeOrdersOutput, ListDelayRiskSuggestionsInput, ListDelayRiskSuggestionsOutput, ListMaterialUsagesInput, ListMaterialUsagesOutput, ListTimeLogsInput, ListTimeLogsOutput, ListWorkTasksInput, ListWorkTasksOutput, TriggerDelayRiskSuggestionsInput, TriggerDelayRiskSuggestionsOutput } from '/_102045_/l2/buildFlowFsm/web/contracts/projectDetailWorkspace.js';

type IsAny<T> = 0 extends (1 & T) ? true : false;
type Assignable<Actual, Expected> = IsAny<Actual> extends true ? false : [Actual] extends [Expected] ? true : false;
type Assert<T extends true> = T;

declare const page: BuildFlowFsmProjectDetailWorkspaceBase;

// This file is generated from .defs.ts. Add narrower state/action assertions here as materialization rules evolve.
type _State_status = Assert<Assignable<typeof page.status, string>>;
type _State_getProjectDetailState = Assert<Assignable<typeof page.getProjectDetailState, "idle" | "loading" | "success" | "error">>;
type _State_getProjectDetailProjectId = Assert<Assignable<typeof page.getProjectDetailProjectId, string | GetProjectDetailInput["projectId"]>>;
type _State_getProjectDetailData = Assert<Assignable<typeof page.getProjectDetailData, GetProjectDetailOutput | null>>;
type _State_listWorkTasksState = Assert<Assignable<typeof page.listWorkTasksState, "idle" | "loading" | "success" | "error">>;
type _State_listWorkTasksProjectId = Assert<Assignable<typeof page.listWorkTasksProjectId, string | ListWorkTasksInput["projectId"]>>;
type _State_listWorkTasksStatus = Assert<Assignable<typeof page.listWorkTasksStatus, string | ListWorkTasksInput["status"]>>;
type _State_listWorkTasksAssignedWorkerId = Assert<Assignable<typeof page.listWorkTasksAssignedWorkerId, string | ListWorkTasksInput["assignedWorkerId"]>>;
type _State_listWorkTasksPage = Assert<Assignable<typeof page.listWorkTasksPage, string | ListWorkTasksInput["page"]>>;
type _State_listWorkTasksPageSize = Assert<Assignable<typeof page.listWorkTasksPageSize, string | ListWorkTasksInput["pageSize"]>>;
type _State_listWorkTasksData = Assert<Assignable<typeof page.listWorkTasksData, ListWorkTasksOutput>>;
type _State_listChangeOrdersState = Assert<Assignable<typeof page.listChangeOrdersState, "idle" | "loading" | "success" | "error">>;
type _State_listChangeOrdersProjectId = Assert<Assignable<typeof page.listChangeOrdersProjectId, string | ListChangeOrdersInput["projectId"]>>;
type _State_listChangeOrdersStatus = Assert<Assignable<typeof page.listChangeOrdersStatus, string | ListChangeOrdersInput["status"]>>;
type _State_listChangeOrdersImpactType = Assert<Assignable<typeof page.listChangeOrdersImpactType, string | ListChangeOrdersInput["impactType"]>>;
type _State_listChangeOrdersPage = Assert<Assignable<typeof page.listChangeOrdersPage, string | ListChangeOrdersInput["page"]>>;
type _State_listChangeOrdersPageSize = Assert<Assignable<typeof page.listChangeOrdersPageSize, string | ListChangeOrdersInput["pageSize"]>>;
type _State_listChangeOrdersData = Assert<Assignable<typeof page.listChangeOrdersData, ListChangeOrdersOutput>>;
type _State_getChangeOrderDetailState = Assert<Assignable<typeof page.getChangeOrderDetailState, "idle" | "loading" | "success" | "error">>;
type _State_getChangeOrderDetailChangeOrderId = Assert<Assignable<typeof page.getChangeOrderDetailChangeOrderId, string | GetChangeOrderDetailInput["changeOrderId"]>>;
type _State_getChangeOrderDetailData = Assert<Assignable<typeof page.getChangeOrderDetailData, GetChangeOrderDetailOutput | null>>;
type _State_listTimeLogsState = Assert<Assignable<typeof page.listTimeLogsState, "idle" | "loading" | "success" | "error">>;
type _State_listTimeLogsWorkTaskId = Assert<Assignable<typeof page.listTimeLogsWorkTaskId, string | ListTimeLogsInput["workTaskId"]>>;
type _State_listTimeLogsWorkerName = Assert<Assignable<typeof page.listTimeLogsWorkerName, string | ListTimeLogsInput["workerName"]>>;
type _State_listTimeLogsLogDate = Assert<Assignable<typeof page.listTimeLogsLogDate, string | ListTimeLogsInput["logDate"]>>;
type _State_listTimeLogsStatus = Assert<Assignable<typeof page.listTimeLogsStatus, string | ListTimeLogsInput["status"]>>;
type _State_listTimeLogsPage = Assert<Assignable<typeof page.listTimeLogsPage, string | ListTimeLogsInput["page"]>>;
type _State_listTimeLogsPageSize = Assert<Assignable<typeof page.listTimeLogsPageSize, string | ListTimeLogsInput["pageSize"]>>;
type _State_listTimeLogsData = Assert<Assignable<typeof page.listTimeLogsData, ListTimeLogsOutput>>;
type _State_listMaterialUsagesState = Assert<Assignable<typeof page.listMaterialUsagesState, "idle" | "loading" | "success" | "error">>;
type _State_listMaterialUsagesProjectId = Assert<Assignable<typeof page.listMaterialUsagesProjectId, string | ListMaterialUsagesInput["projectId"]>>;
type _State_listMaterialUsagesStatus = Assert<Assignable<typeof page.listMaterialUsagesStatus, string | ListMaterialUsagesInput["status"]>>;
type _State_listMaterialUsagesPage = Assert<Assignable<typeof page.listMaterialUsagesPage, string | ListMaterialUsagesInput["page"]>>;
type _State_listMaterialUsagesPageSize = Assert<Assignable<typeof page.listMaterialUsagesPageSize, string | ListMaterialUsagesInput["pageSize"]>>;
type _State_listMaterialUsagesData = Assert<Assignable<typeof page.listMaterialUsagesData, ListMaterialUsagesOutput>>;
type _State_triggerDelayRiskSuggestionsState = Assert<Assignable<typeof page.triggerDelayRiskSuggestionsState, "idle" | "loading" | "success" | "error">>;
type _State_triggerDelayRiskSuggestionsStatusReportId = Assert<Assignable<typeof page.triggerDelayRiskSuggestionsStatusReportId, string | TriggerDelayRiskSuggestionsInput["statusReportId"]>>;
type _State_triggerDelayRiskSuggestionsOutput = Assert<Assignable<typeof page.triggerDelayRiskSuggestionsOutput, TriggerDelayRiskSuggestionsOutput | null>>;
type _State_triggerDelayRiskSuggestionsError = Assert<Assignable<typeof page.triggerDelayRiskSuggestionsError, string>>;
type _State_listDelayRiskSuggestionsState = Assert<Assignable<typeof page.listDelayRiskSuggestionsState, "idle" | "loading" | "success" | "error">>;
type _State_listDelayRiskSuggestionsStatusReportId = Assert<Assignable<typeof page.listDelayRiskSuggestionsStatusReportId, string | ListDelayRiskSuggestionsInput["statusReportId"]>>;
type _State_listDelayRiskSuggestionsAcknowledged = Assert<Assignable<typeof page.listDelayRiskSuggestionsAcknowledged, string | ListDelayRiskSuggestionsInput["acknowledged"]>>;
type _State_listDelayRiskSuggestionsData = Assert<Assignable<typeof page.listDelayRiskSuggestionsData, unknown[] | ListDelayRiskSuggestionsOutput>>;
type _Action_loadGetProjectDetail = Assert<Assignable<typeof page.loadGetProjectDetail, (...args: any[]) => unknown>>;
type _Handler_handleGetProjectDetailClick = Assert<Assignable<typeof page.handleGetProjectDetailClick, (...args: any[]) => unknown>>;
type _Action_loadListWorkTasks = Assert<Assignable<typeof page.loadListWorkTasks, (...args: any[]) => unknown>>;
type _Handler_handleListWorkTasksClick = Assert<Assignable<typeof page.handleListWorkTasksClick, (...args: any[]) => unknown>>;
type _Action_loadListChangeOrders = Assert<Assignable<typeof page.loadListChangeOrders, (...args: any[]) => unknown>>;
type _Handler_handleListChangeOrdersClick = Assert<Assignable<typeof page.handleListChangeOrdersClick, (...args: any[]) => unknown>>;
type _Action_loadGetChangeOrderDetail = Assert<Assignable<typeof page.loadGetChangeOrderDetail, (...args: any[]) => unknown>>;
type _Handler_handleGetChangeOrderDetailClick = Assert<Assignable<typeof page.handleGetChangeOrderDetailClick, (...args: any[]) => unknown>>;
type _Action_loadListTimeLogs = Assert<Assignable<typeof page.loadListTimeLogs, (...args: any[]) => unknown>>;
type _Handler_handleListTimeLogsClick = Assert<Assignable<typeof page.handleListTimeLogsClick, (...args: any[]) => unknown>>;
type _Action_loadListMaterialUsages = Assert<Assignable<typeof page.loadListMaterialUsages, (...args: any[]) => unknown>>;
type _Handler_handleListMaterialUsagesClick = Assert<Assignable<typeof page.handleListMaterialUsagesClick, (...args: any[]) => unknown>>;
type _Action_triggerDelayRiskSuggestions = Assert<Assignable<typeof page.triggerDelayRiskSuggestions, (...args: any[]) => unknown>>;
type _Handler_handleTriggerDelayRiskSuggestionsClick = Assert<Assignable<typeof page.handleTriggerDelayRiskSuggestionsClick, (...args: any[]) => unknown>>;
type _Action_loadListDelayRiskSuggestions = Assert<Assignable<typeof page.loadListDelayRiskSuggestions, (...args: any[]) => unknown>>;
type _Handler_handleListDelayRiskSuggestionsClick = Assert<Assignable<typeof page.handleListDelayRiskSuggestionsClick, (...args: any[]) => unknown>>;
type _Action_setGetProjectDetailProjectId = Assert<Assignable<typeof page.setGetProjectDetailProjectId, (...args: any[]) => unknown>>;
type _Handler_handleGetProjectDetailProjectIdChange = Assert<Assignable<typeof page.handleGetProjectDetailProjectIdChange, (...args: any[]) => unknown>>;
type _Action_setListWorkTasksProjectId = Assert<Assignable<typeof page.setListWorkTasksProjectId, (...args: any[]) => unknown>>;
type _Handler_handleListWorkTasksProjectIdChange = Assert<Assignable<typeof page.handleListWorkTasksProjectIdChange, (...args: any[]) => unknown>>;
type _Action_setListWorkTasksStatus = Assert<Assignable<typeof page.setListWorkTasksStatus, (...args: any[]) => unknown>>;
type _Handler_handleListWorkTasksStatusChange = Assert<Assignable<typeof page.handleListWorkTasksStatusChange, (...args: any[]) => unknown>>;
type _Action_setListWorkTasksAssignedWorkerId = Assert<Assignable<typeof page.setListWorkTasksAssignedWorkerId, (...args: any[]) => unknown>>;
type _Handler_handleListWorkTasksAssignedWorkerIdChange = Assert<Assignable<typeof page.handleListWorkTasksAssignedWorkerIdChange, (...args: any[]) => unknown>>;
type _Action_setListWorkTasksPage = Assert<Assignable<typeof page.setListWorkTasksPage, (...args: any[]) => unknown>>;
type _Handler_handleListWorkTasksPageChange = Assert<Assignable<typeof page.handleListWorkTasksPageChange, (...args: any[]) => unknown>>;
type _Action_setListWorkTasksPageSize = Assert<Assignable<typeof page.setListWorkTasksPageSize, (...args: any[]) => unknown>>;
type _Handler_handleListWorkTasksPageSizeChange = Assert<Assignable<typeof page.handleListWorkTasksPageSizeChange, (...args: any[]) => unknown>>;
type _Action_setListChangeOrdersProjectId = Assert<Assignable<typeof page.setListChangeOrdersProjectId, (...args: any[]) => unknown>>;
type _Handler_handleListChangeOrdersProjectIdChange = Assert<Assignable<typeof page.handleListChangeOrdersProjectIdChange, (...args: any[]) => unknown>>;
type _Action_setListChangeOrdersStatus = Assert<Assignable<typeof page.setListChangeOrdersStatus, (...args: any[]) => unknown>>;
type _Handler_handleListChangeOrdersStatusChange = Assert<Assignable<typeof page.handleListChangeOrdersStatusChange, (...args: any[]) => unknown>>;
type _Action_setListChangeOrdersImpactType = Assert<Assignable<typeof page.setListChangeOrdersImpactType, (...args: any[]) => unknown>>;
type _Handler_handleListChangeOrdersImpactTypeChange = Assert<Assignable<typeof page.handleListChangeOrdersImpactTypeChange, (...args: any[]) => unknown>>;
type _Action_setListChangeOrdersPage = Assert<Assignable<typeof page.setListChangeOrdersPage, (...args: any[]) => unknown>>;
type _Handler_handleListChangeOrdersPageChange = Assert<Assignable<typeof page.handleListChangeOrdersPageChange, (...args: any[]) => unknown>>;
type _Action_setListChangeOrdersPageSize = Assert<Assignable<typeof page.setListChangeOrdersPageSize, (...args: any[]) => unknown>>;
type _Handler_handleListChangeOrdersPageSizeChange = Assert<Assignable<typeof page.handleListChangeOrdersPageSizeChange, (...args: any[]) => unknown>>;
type _Action_setGetChangeOrderDetailChangeOrderId = Assert<Assignable<typeof page.setGetChangeOrderDetailChangeOrderId, (...args: any[]) => unknown>>;
type _Handler_handleGetChangeOrderDetailChangeOrderIdChange = Assert<Assignable<typeof page.handleGetChangeOrderDetailChangeOrderIdChange, (...args: any[]) => unknown>>;
type _Action_setListTimeLogsWorkTaskId = Assert<Assignable<typeof page.setListTimeLogsWorkTaskId, (...args: any[]) => unknown>>;
type _Handler_handleListTimeLogsWorkTaskIdChange = Assert<Assignable<typeof page.handleListTimeLogsWorkTaskIdChange, (...args: any[]) => unknown>>;
type _Action_setListTimeLogsWorkerName = Assert<Assignable<typeof page.setListTimeLogsWorkerName, (...args: any[]) => unknown>>;
type _Handler_handleListTimeLogsWorkerNameChange = Assert<Assignable<typeof page.handleListTimeLogsWorkerNameChange, (...args: any[]) => unknown>>;
type _Action_setListTimeLogsLogDate = Assert<Assignable<typeof page.setListTimeLogsLogDate, (...args: any[]) => unknown>>;
type _Handler_handleListTimeLogsLogDateChange = Assert<Assignable<typeof page.handleListTimeLogsLogDateChange, (...args: any[]) => unknown>>;
type _Action_setListTimeLogsStatus = Assert<Assignable<typeof page.setListTimeLogsStatus, (...args: any[]) => unknown>>;
type _Handler_handleListTimeLogsStatusChange = Assert<Assignable<typeof page.handleListTimeLogsStatusChange, (...args: any[]) => unknown>>;
type _Action_setListTimeLogsPage = Assert<Assignable<typeof page.setListTimeLogsPage, (...args: any[]) => unknown>>;
type _Handler_handleListTimeLogsPageChange = Assert<Assignable<typeof page.handleListTimeLogsPageChange, (...args: any[]) => unknown>>;
type _Action_setListTimeLogsPageSize = Assert<Assignable<typeof page.setListTimeLogsPageSize, (...args: any[]) => unknown>>;
type _Handler_handleListTimeLogsPageSizeChange = Assert<Assignable<typeof page.handleListTimeLogsPageSizeChange, (...args: any[]) => unknown>>;
type _Action_setListMaterialUsagesProjectId = Assert<Assignable<typeof page.setListMaterialUsagesProjectId, (...args: any[]) => unknown>>;
type _Handler_handleListMaterialUsagesProjectIdChange = Assert<Assignable<typeof page.handleListMaterialUsagesProjectIdChange, (...args: any[]) => unknown>>;
type _Action_setListMaterialUsagesStatus = Assert<Assignable<typeof page.setListMaterialUsagesStatus, (...args: any[]) => unknown>>;
type _Handler_handleListMaterialUsagesStatusChange = Assert<Assignable<typeof page.handleListMaterialUsagesStatusChange, (...args: any[]) => unknown>>;
type _Action_setListMaterialUsagesPage = Assert<Assignable<typeof page.setListMaterialUsagesPage, (...args: any[]) => unknown>>;
type _Handler_handleListMaterialUsagesPageChange = Assert<Assignable<typeof page.handleListMaterialUsagesPageChange, (...args: any[]) => unknown>>;
type _Action_setListMaterialUsagesPageSize = Assert<Assignable<typeof page.setListMaterialUsagesPageSize, (...args: any[]) => unknown>>;
type _Handler_handleListMaterialUsagesPageSizeChange = Assert<Assignable<typeof page.handleListMaterialUsagesPageSizeChange, (...args: any[]) => unknown>>;
type _Action_setTriggerDelayRiskSuggestionsStatusReportId = Assert<Assignable<typeof page.setTriggerDelayRiskSuggestionsStatusReportId, (...args: any[]) => unknown>>;
type _Handler_handleTriggerDelayRiskSuggestionsStatusReportIdChange = Assert<Assignable<typeof page.handleTriggerDelayRiskSuggestionsStatusReportIdChange, (...args: any[]) => unknown>>;
type _Action_setListDelayRiskSuggestionsStatusReportId = Assert<Assignable<typeof page.setListDelayRiskSuggestionsStatusReportId, (...args: any[]) => unknown>>;
type _Handler_handleListDelayRiskSuggestionsStatusReportIdChange = Assert<Assignable<typeof page.handleListDelayRiskSuggestionsStatusReportIdChange, (...args: any[]) => unknown>>;
type _Action_setListDelayRiskSuggestionsAcknowledged = Assert<Assignable<typeof page.setListDelayRiskSuggestionsAcknowledged, (...args: any[]) => unknown>>;
type _Handler_handleListDelayRiskSuggestionsAcknowledgedChange = Assert<Assignable<typeof page.handleListDelayRiskSuggestionsAcknowledgedChange, (...args: any[]) => unknown>>;

export {};