/// <mls fileReference="_102045_/l2/buildFlowFsm/web/shared/taskBoardWorkspace.test.ts" enhancement="_102020_/l2/enhancementAura"/>

import type { BuildFlowFsmTaskBoardWorkspaceBase } from '/_102045_/l2/buildFlowFsm/web/shared/taskBoardWorkspace.js';
import type { CmdCreateWorkTaskInput, CmdCreateWorkTaskOutput, CmdUpdateWorkTaskInput, CmdUpdateWorkTaskOutput, CmdUpdateWorkTaskStatusInput, CmdUpdateWorkTaskStatusOutput } from '/_102045_/l2/buildFlowFsm/web/contracts/taskBoardWorkspace.js';

type IsAny<T> = 0 extends (1 & T) ? true : false;
type Assignable<Actual, Expected> = IsAny<Actual> extends true ? false : [Actual] extends [Expected] ? true : false;
type Assert<T extends true> = T;

declare const page: BuildFlowFsmTaskBoardWorkspaceBase;

// This file is generated from .defs.ts. Add narrower state/action assertions here as materialization rules evolve.
type _State_status = Assert<Assignable<typeof page.status, string>>;
type _State_cmdCreateWorkTaskState = Assert<Assignable<typeof page.cmdCreateWorkTaskState, "idle" | "loading" | "success" | "error">>;
type _State_cmdCreateWorkTaskProjectId = Assert<Assignable<typeof page.cmdCreateWorkTaskProjectId, string | CmdCreateWorkTaskInput["projectId"]>>;
type _State_cmdCreateWorkTaskTitle = Assert<Assignable<typeof page.cmdCreateWorkTaskTitle, string | CmdCreateWorkTaskInput["title"]>>;
type _State_cmdCreateWorkTaskDescription = Assert<Assignable<typeof page.cmdCreateWorkTaskDescription, string | CmdCreateWorkTaskInput["description"]>>;
type _State_cmdCreateWorkTaskAssignedWorkerId = Assert<Assignable<typeof page.cmdCreateWorkTaskAssignedWorkerId, string | CmdCreateWorkTaskInput["assignedWorkerId"]>>;
type _State_cmdCreateWorkTaskDueDate = Assert<Assignable<typeof page.cmdCreateWorkTaskDueDate, string | CmdCreateWorkTaskInput["dueDate"]>>;
type _State_cmdCreateWorkTaskOutput = Assert<Assignable<typeof page.cmdCreateWorkTaskOutput, CmdCreateWorkTaskOutput | null>>;
type _State_cmdCreateWorkTaskError = Assert<Assignable<typeof page.cmdCreateWorkTaskError, string>>;
type _State_cmdUpdateWorkTaskState = Assert<Assignable<typeof page.cmdUpdateWorkTaskState, "idle" | "loading" | "success" | "error">>;
type _State_cmdUpdateWorkTaskWorkTaskId = Assert<Assignable<typeof page.cmdUpdateWorkTaskWorkTaskId, string | CmdUpdateWorkTaskInput["workTaskId"]>>;
type _State_cmdUpdateWorkTaskTitle = Assert<Assignable<typeof page.cmdUpdateWorkTaskTitle, string | CmdUpdateWorkTaskInput["title"]>>;
type _State_cmdUpdateWorkTaskDescription = Assert<Assignable<typeof page.cmdUpdateWorkTaskDescription, string | CmdUpdateWorkTaskInput["description"]>>;
type _State_cmdUpdateWorkTaskAssignedWorkerId = Assert<Assignable<typeof page.cmdUpdateWorkTaskAssignedWorkerId, string | CmdUpdateWorkTaskInput["assignedWorkerId"]>>;
type _State_cmdUpdateWorkTaskDueDate = Assert<Assignable<typeof page.cmdUpdateWorkTaskDueDate, string | CmdUpdateWorkTaskInput["dueDate"]>>;
type _State_cmdUpdateWorkTaskStatusValue = Assert<Assignable<typeof page.cmdUpdateWorkTaskStatusValue, string | CmdUpdateWorkTaskInput["status"]>>;
type _State_cmdUpdateWorkTaskCancellationReason = Assert<Assignable<typeof page.cmdUpdateWorkTaskCancellationReason, string | CmdUpdateWorkTaskInput["cancellationReason"]>>;
type _State_cmdUpdateWorkTaskOutput = Assert<Assignable<typeof page.cmdUpdateWorkTaskOutput, CmdUpdateWorkTaskOutput | null>>;
type _State_cmdUpdateWorkTaskError = Assert<Assignable<typeof page.cmdUpdateWorkTaskError, string>>;
type _State_cmdUpdateWorkTaskStatusState = Assert<Assignable<typeof page.cmdUpdateWorkTaskStatusState, "idle" | "loading" | "success" | "error">>;
type _State_cmdUpdateWorkTaskStatusWorkTaskId = Assert<Assignable<typeof page.cmdUpdateWorkTaskStatusWorkTaskId, string | CmdUpdateWorkTaskStatusInput["workTaskId"]>>;
type _State_cmdUpdateWorkTaskStatusStatus = Assert<Assignable<typeof page.cmdUpdateWorkTaskStatusStatus, string | CmdUpdateWorkTaskStatusInput["status"]>>;
type _State_cmdUpdateWorkTaskStatusCancellationReason = Assert<Assignable<typeof page.cmdUpdateWorkTaskStatusCancellationReason, string | CmdUpdateWorkTaskStatusInput["cancellationReason"]>>;
type _State_cmdUpdateWorkTaskStatusCompletedAt = Assert<Assignable<typeof page.cmdUpdateWorkTaskStatusCompletedAt, string | CmdUpdateWorkTaskStatusInput["completedAt"]>>;
type _State_cmdUpdateWorkTaskStatusActorId = Assert<Assignable<typeof page.cmdUpdateWorkTaskStatusActorId, string | CmdUpdateWorkTaskStatusInput["actorId"]>>;
type _State_cmdUpdateWorkTaskStatusOutput = Assert<Assignable<typeof page.cmdUpdateWorkTaskStatusOutput, CmdUpdateWorkTaskStatusOutput | null>>;
type _State_cmdUpdateWorkTaskStatusError = Assert<Assignable<typeof page.cmdUpdateWorkTaskStatusError, string>>;
type _Action_cmdCreateWorkTask = Assert<Assignable<typeof page.cmdCreateWorkTask, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateWorkTaskClick = Assert<Assignable<typeof page.handleCmdCreateWorkTaskClick, (...args: any[]) => unknown>>;
type _Action_cmdUpdateWorkTask = Assert<Assignable<typeof page.cmdUpdateWorkTask, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateWorkTaskClick = Assert<Assignable<typeof page.handleCmdUpdateWorkTaskClick, (...args: any[]) => unknown>>;
type _Action_cmdUpdateWorkTaskStatus = Assert<Assignable<typeof page.cmdUpdateWorkTaskStatus, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateWorkTaskStatusClick = Assert<Assignable<typeof page.handleCmdUpdateWorkTaskStatusClick, (...args: any[]) => unknown>>;
type _Action_setCmdCreateWorkTaskProjectId = Assert<Assignable<typeof page.setCmdCreateWorkTaskProjectId, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateWorkTaskProjectIdChange = Assert<Assignable<typeof page.handleCmdCreateWorkTaskProjectIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateWorkTaskTitle = Assert<Assignable<typeof page.setCmdCreateWorkTaskTitle, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateWorkTaskTitleChange = Assert<Assignable<typeof page.handleCmdCreateWorkTaskTitleChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateWorkTaskDescription = Assert<Assignable<typeof page.setCmdCreateWorkTaskDescription, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateWorkTaskDescriptionChange = Assert<Assignable<typeof page.handleCmdCreateWorkTaskDescriptionChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateWorkTaskAssignedWorkerId = Assert<Assignable<typeof page.setCmdCreateWorkTaskAssignedWorkerId, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateWorkTaskAssignedWorkerIdChange = Assert<Assignable<typeof page.handleCmdCreateWorkTaskAssignedWorkerIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateWorkTaskDueDate = Assert<Assignable<typeof page.setCmdCreateWorkTaskDueDate, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateWorkTaskDueDateChange = Assert<Assignable<typeof page.handleCmdCreateWorkTaskDueDateChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateWorkTaskWorkTaskId = Assert<Assignable<typeof page.setCmdUpdateWorkTaskWorkTaskId, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateWorkTaskWorkTaskIdChange = Assert<Assignable<typeof page.handleCmdUpdateWorkTaskWorkTaskIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateWorkTaskTitle = Assert<Assignable<typeof page.setCmdUpdateWorkTaskTitle, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateWorkTaskTitleChange = Assert<Assignable<typeof page.handleCmdUpdateWorkTaskTitleChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateWorkTaskDescription = Assert<Assignable<typeof page.setCmdUpdateWorkTaskDescription, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateWorkTaskDescriptionChange = Assert<Assignable<typeof page.handleCmdUpdateWorkTaskDescriptionChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateWorkTaskAssignedWorkerId = Assert<Assignable<typeof page.setCmdUpdateWorkTaskAssignedWorkerId, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateWorkTaskAssignedWorkerIdChange = Assert<Assignable<typeof page.handleCmdUpdateWorkTaskAssignedWorkerIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateWorkTaskDueDate = Assert<Assignable<typeof page.setCmdUpdateWorkTaskDueDate, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateWorkTaskDueDateChange = Assert<Assignable<typeof page.handleCmdUpdateWorkTaskDueDateChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateWorkTaskStatusValue = Assert<Assignable<typeof page.setCmdUpdateWorkTaskStatusValue, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateWorkTaskStatusValueChange = Assert<Assignable<typeof page.handleCmdUpdateWorkTaskStatusValueChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateWorkTaskCancellationReason = Assert<Assignable<typeof page.setCmdUpdateWorkTaskCancellationReason, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateWorkTaskCancellationReasonChange = Assert<Assignable<typeof page.handleCmdUpdateWorkTaskCancellationReasonChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateWorkTaskStatusWorkTaskId = Assert<Assignable<typeof page.setCmdUpdateWorkTaskStatusWorkTaskId, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateWorkTaskStatusWorkTaskIdChange = Assert<Assignable<typeof page.handleCmdUpdateWorkTaskStatusWorkTaskIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateWorkTaskStatusStatus = Assert<Assignable<typeof page.setCmdUpdateWorkTaskStatusStatus, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateWorkTaskStatusStatusChange = Assert<Assignable<typeof page.handleCmdUpdateWorkTaskStatusStatusChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateWorkTaskStatusCancellationReason = Assert<Assignable<typeof page.setCmdUpdateWorkTaskStatusCancellationReason, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateWorkTaskStatusCancellationReasonChange = Assert<Assignable<typeof page.handleCmdUpdateWorkTaskStatusCancellationReasonChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateWorkTaskStatusCompletedAt = Assert<Assignable<typeof page.setCmdUpdateWorkTaskStatusCompletedAt, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateWorkTaskStatusCompletedAtChange = Assert<Assignable<typeof page.handleCmdUpdateWorkTaskStatusCompletedAtChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateWorkTaskStatusActorId = Assert<Assignable<typeof page.setCmdUpdateWorkTaskStatusActorId, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateWorkTaskStatusActorIdChange = Assert<Assignable<typeof page.handleCmdUpdateWorkTaskStatusActorIdChange, (...args: any[]) => unknown>>;

export {};